export const ERROR_CODES = {
  // Auth
  INVALID_OTP: 'INVALID_OTP',
  EXPIRED_OTP: 'EXPIRED_OTP',
  LOCKED_OUT: 'LOCKED_OUT',
  RATE_LIMIT: 'RATE_LIMIT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  SUSPENDED: 'SUSPENDED',
  // Authorization
  FORBIDDEN: 'FORBIDDEN',
  NOT_ADMIN: 'NOT_ADMIN',
  NOT_VERIFIED: 'NOT_VERIFIED',
  NOT_OWNER: 'NOT_OWNER',
  // Validation
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_PHONE: 'INVALID_PHONE',
  // Business logic
  DUPLICATE: 'DUPLICATE',
  NOT_FOUND: 'NOT_FOUND',
  LISTING_INACTIVE: 'LISTING_INACTIVE',
  BOTH_NOT_VERIFIED: 'BOTH_NOT_VERIFIED',
  // Storage
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
