/**
 * Metro Manila cities and barangays for listing filters.
 * Cities sorted alphabetically. Barangays sorted alphabetically within each city.
 * For cities with numbered barangays (Manila, Caloocan, Pasay), district/area names are used instead.
 */
export const METRO_MANILA: Record<string, string[]> = {
  "Caloocan": [
    "Bagbaguin", "Bagong Barrio East", "Bagong Barrio West", "Bagong Silang",
    "Bagumbong", "Balintawak", "Barrio San Jose", "Camarin", "Congress",
    "Dagat-Dagatan", "Deparo", "Grace Park East", "Grace Park West",
    "Kaybiga", "Kaunlaran Village", "Libis Baesa", "Libis Reparo", "Llano",
    "Marulas", "Maypajo", "Poblacion", "Sangandaan", "Santa Quiteria",
    "Talipapa", "Urduja Village",
  ],
  "Las Piñas": [
    "Almanza Dos", "Almanza Uno", "B.F. International Village", "Daniel Fajardo",
    "Elias Aldana", "Ilaya", "Manuyo Dos", "Manuyo Uno", "Pamplona Dos",
    "Pamplona Tres", "Pamplona Uno", "Pilar", "Pulang Lupa Dos",
    "Pulang Lupa Uno", "Talon Dos", "Talon Kuatro", "Talon Singko",
    "Talon Tres", "Talon Uno", "Zapote",
  ],
  "Makati": [
    "Bangkal", "Bel-Air", "Carmona", "Dasmariñas", "Forbes Park",
    "Guadalupe Nuevo", "Guadalupe Viejo", "Kasilawan", "La Paz",
    "Magallanes", "Olympia", "Palanan", "Pinagkaisahan", "Pio del Pilar",
    "Poblacion", "San Antonio", "San Isidro", "San Lorenzo", "Santa Cruz",
    "Singkamas", "Tejeros", "Urdaneta", "Valenzuela",
  ],
  "Malabon": [
    "Acacia", "Baritan", "Bayan-Bayanan", "Catmon", "Concepcion",
    "Dampalit", "Flores", "Hulong Duhat", "Ibaba", "Longos", "Maysilo",
    "Muzon", "Niugan", "Panghulo", "Potrero", "San Agustin", "Santolan",
    "Tanong", "Tinajeros", "Tonsuya", "Tugatog",
  ],
  "Mandaluyong": [
    "Addition Hills", "Bagong Silang", "Barangka Drive", "Barangka Ibaba",
    "Barangka Ilaya", "Barangka Itaas", "Buayang Bato", "Burol",
    "Daang Bakal", "Hagdang Bato Itaas", "Hagdang Bato Libis",
    "Harapin Ang Bukas", "Highway Hills", "Hulo", "Mabini-J. Rizal",
    "Malamig", "Mauway", "Namayan", "New Zaniga", "Old Zaniga",
    "Pag-asa", "Plainview", "Pleasant Hills", "Poblacion", "San Jose",
    "Vergara", "Wack-Wack Greenhills",
  ],
  "Manila": [
    "Binondo", "Ermita", "Intramuros", "Malate", "Paco", "Pandacan",
    "Port Area", "Quiapo", "Sampaloc", "San Andres", "San Miguel",
    "San Nicolas", "Santa Ana", "Santa Cruz", "Santa Mesa", "Tondo",
  ],
  "Marikina": [
    "Barangka", "Concepcion Dos", "Concepcion Uno", "Fortune",
    "Industrial Valley", "Jesus dela Peña", "Kalumpang", "Malanday",
    "Marikina Heights", "Nangka", "Parang", "San Roque", "Santa Elena",
    "Santo Niño", "Tañong", "Tumana",
  ],
  "Muntinlupa": [
    "Alabang", "Ayala Alabang", "Bayanan", "Buli", "Cupang",
    "Poblacion", "Putatan", "Sucat", "Tunasan",
  ],
  "Navotas": [
    "Bagumbayan North", "Bagumbayan South", "Bangculasi", "Daanghari",
    "Navotas East", "Navotas West", "NBBS Dagat-Dagatan", "NBBS Kaunlaran",
    "NBBS Proper", "North Bay Boulevard North", "San Jose",
    "San Rafael Village", "San Roque", "Sipac-Almacen", "Tangos North",
    "Tangos South", "Tanza 1", "Tanza 2",
  ],
  "Parañaque": [
    "Baclaran", "BF Homes", "Don Bosco", "Don Galo", "La Huerta",
    "Marcelo Green", "Merville", "Moonwalk", "San Antonio", "San Dionisio",
    "San Isidro", "San Martin de Porres", "Santo Niño", "Sun Valley",
    "Tambo", "Vitalez",
  ],
  "Pasay": [
    "Baclaran", "Bay City", "Cartimar", "CCP Complex", "Edsa",
    "Libertad", "Malibay", "Newport City", "Pasay City Proper",
    "Pildera", "Rotonda", "Santa Clara", "Tramo", "Villamor Airbase",
  ],
  "Pasig": [
    "Bagong Ilog", "Bagong Katipunan", "Bambang", "Buting", "Caniogan",
    "Dela Paz", "Kalawaan", "Kapasigan", "Kapitolyo", "Malinao",
    "Manggahan", "Maybunga", "Oranbo", "Palatiw", "Pinagbuhatan",
    "Pineda", "Rosario", "Sagad", "San Antonio", "San Joaquin",
    "San Jose", "San Miguel", "San Nicolas", "Santa Cruz", "Santa Lucia",
    "Santa Rosa", "Santo Tomas", "Santolan", "Sumilang", "Ugong",
  ],
  "Pateros": [
    "Aguho", "Magtanggol", "Martires Del 96", "Poblacion", "San Pedro",
    "San Roque", "Santa Ana", "Santo Rosario-Kanluran",
    "Santo Rosario-Silangan", "Tabacalera",
  ],
  "Quezon City": [
    "Alicia", "Amihan", "Apolonio Samson", "Aurora", "Baesa", "Bagbag",
    "Bagong Lipunan ng Crame", "Bagong Pag-asa", "Bagong Silangan",
    "Bagumbayan", "Bagumbuhay", "Bahay Toro", "Balingasa", "Balong Bato",
    "Batasan Hills", "Bayanihan", "Blue Ridge A", "Blue Ridge B",
    "Botocan", "Bungad", "Camp Aguinaldo", "Capri", "Central", "Claro",
    "Commonwealth", "Culiat", "Damar", "Damayan", "Damayang Lagi",
    "Del Monte", "Dioquino Zobel", "Don Manuel", "Doña Imelda",
    "Doña Josefa", "Duyan-Duyan", "E. Rodriguez", "East Kamias",
    "Escopa I", "Escopa II", "Escopa III", "Escopa IV", "Fairview",
    "Greater Lagro", "Gulod", "Holy Spirit", "Horseshoe",
    "Immaculate Concepcion", "Kaligayahan", "Kalusugan", "Kamuning",
    "Katipunan", "Kaunlaran", "Kristong Hari", "Krus na Ligas",
    "Laging Handa", "Libis", "Lourdes", "Loyola Heights", "Maharlika",
    "Malaya", "Mangga", "Manresa", "Mariana", "Mariblo", "Marilag",
    "Masagana", "Masambong", "Matandang Balara", "Milagrosa",
    "N.S. Amoranto", "Nagkaisang Nayon", "Nayong Kanluran", "New Era",
    "North Fairview", "Novaliches Proper", "Obrero", "Old Capitol Site",
    "Paang Bundok", "Pag-ibig sa Nayon", "Paligsahan", "Paltok",
    "Pansol", "Paraiso", "Pasong Putik Proper", "Pasong Tamo", "Payatas",
    "Phil-Am", "Pinagkaisahan", "Pinyahan", "Project 6", "Quirino 2-A",
    "Quirino 2-B", "Quirino 2-C", "Quirino 3-A", "Ramon Magsaysay",
    "Roxas", "Sacred Heart", "Saint Ignatius", "Saint Peter", "Salvacion",
    "San Agustin", "San Antonio", "San Bartolome", "San Isidro",
    "San Isidro Labrador", "San Jose", "San Martin de Porres",
    "San Roque", "San Vicente", "Sangandaan", "Santa Cruz",
    "Santa Lucia", "Santa Monica", "Santa Teresita", "Santo Cristo",
    "Santo Domingo", "Santo Niño", "Santol", "Sauyo", "Sienna",
    "Sikatuna Village", "Silangan", "Socorro", "South Triangle",
    "Tagumpay", "Talayan", "Talipapa", "Tandang Sora", "Tatalon",
    "Teachers Village East", "Teachers Village West", "U.P. Campus",
    "U.P. Village", "Ugong Norte", "Unang Sigaw", "Valencia", "Vasra",
    "Veterans Village", "Villa Maria Clara", "West Kamias",
    "West Triangle", "White Plains",
  ],
  "San Juan": [
    "Addition Hills", "Balong-Bato", "Batis", "Corazon de Jesus",
    "Ermitaño", "Greenhills", "Isabelita", "Kabayanan", "Little Baguio",
    "Maytunas", "Onse", "Pasadena", "Pedro Cruz", "Progreso", "Rivera",
    "Salapan", "San Perfecto", "Santa Lucia", "St. Joseph", "Tibagan",
    "West Crame",
  ],
  "Taguig": [
    "Bagumbayan", "Bambang", "Calzada", "Cembo", "Central Bicutan",
    "Central Signal Village", "Comembo", "East Rembo", "Fort Bonifacio",
    "Hagonoy", "Ibayo-Tipas", "Katuparan", "Ligid-Tipas",
    "Lower Bicutan", "Maharlika Village", "Napindan", "New Lower Bicutan",
    "North Daang Hari", "North Signal Village", "Palingon", "Pembo",
    "Pinagsama", "Pitogo", "Post Proper Northside", "Post Proper Southside",
    "Rizal", "San Miguel", "Santa Ana", "South Cembo", "South Daang Hari",
    "South Signal Village", "Tanyag", "Tuktukan", "Upper Bicutan",
    "Ususan", "Wawa", "West Rembo", "Western Bicutan",
  ],
  "Valenzuela": [
    "Arkong Bato", "Bagbaguin", "Balangkas", "Bignay", "Bisig",
    "Canumay East", "Canumay West", "Coloong", "Dalandanan",
    "Gen. T. de Leon", "Isla", "Karuhatan", "Lawang Bato", "Lingunan",
    "Mabolo", "Malanday", "Malinta", "Mapulang Lupa", "Marulas",
    "Maysan", "Palasan", "Parada", "Pariancillo Villa", "Paso de Blas",
    "Pasolo", "Poblacion", "Polo", "Punturin", "Rincon", "Tagalag",
    "Ugong", "Veinte Reales", "Wawang Pulo",
  ],
};

export const METRO_MANILA_CITIES = Object.keys(METRO_MANILA).sort();
