#!/bin/bash
# .claude-brain/scripts/refresh-repo-status.sh
# Regenerates .claude-brain/context/02-repo-status.md with current ground truth.
# Run at the start of every work session.

set -e

BRAIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATUS_FILE="$BRAIN_DIR/context/02-repo-status.md"
REPO_ROOT="$(cd "$BRAIN_DIR/.." && pwd)"

cd "$REPO_ROOT"

# Start fresh
cat > "$STATUS_FILE" << 'EOF'
# Repo Status — Current Code State

**⚠️ This file is auto-generated by `.claude-brain/scripts/refresh-repo-status.sh`. Do not edit manually.**

EOF

echo "**Last refresh:** $(date '+%Y-%m-%d %H:%M:%S %Z')" >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"
echo "---" >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"

# ============================================================================
# Git status
# ============================================================================
echo "## Git status" >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"
echo "**Branch:** $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'not a git repo')" >> "$STATUS_FILE"
echo "**Last commit:** $(git log -1 --oneline 2>/dev/null || echo 'no commits yet')" >> "$STATUS_FILE"
echo "**Uncommitted changes:**" >> "$STATUS_FILE"
echo '```' >> "$STATUS_FILE"
git status --short 2>/dev/null | head -20 >> "$STATUS_FILE" || echo "not a git repo" >> "$STATUS_FILE"
echo '```' >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"

# ============================================================================
# Line counts
# ============================================================================
echo "## Line counts by package" >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"
echo '```' >> "$STATUS_FILE"

if [ -d "apps/api/src" ]; then
  API_LINES=$(find apps/api/src -name "*.ts" 2>/dev/null | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}')
  echo "apps/api/src:    ${API_LINES:-0} lines" >> "$STATUS_FILE"
fi

if [ -d "apps/mobile/app" ]; then
  MOBILE_LINES=$(find apps/mobile -name "*.ts" -o -name "*.tsx" 2>/dev/null | grep -v node_modules | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}')
  echo "apps/mobile:     ${MOBILE_LINES:-0} lines" >> "$STATUS_FILE"
fi

if [ -d "apps/web/app" ]; then
  WEB_LINES=$(find apps/web -name "*.ts" -o -name "*.tsx" 2>/dev/null | grep -v node_modules | grep -v ".next" | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}')
  echo "apps/web:        ${WEB_LINES:-0} lines" >> "$STATUS_FILE"
fi

if [ -d "packages" ]; then
  PACKAGES_LINES=$(find packages -name "*.ts" -o -name "*.tsx" 2>/dev/null | grep -v node_modules | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}')
  echo "packages:        ${PACKAGES_LINES:-0} lines" >> "$STATUS_FILE"
fi

echo '```' >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"

# ============================================================================
# Current TODOs in source
# ============================================================================
echo "## Current TODOs in source" >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"
echo '```' >> "$STATUS_FILE"
if [ -d "apps" ]; then
  grep -rn "TODO\|FIXME" apps/ --include="*.ts" --include="*.tsx" 2>/dev/null | grep -v node_modules | head -30 >> "$STATUS_FILE" || echo "No TODOs found" >> "$STATUS_FILE"
fi
echo '```' >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"

TODO_COUNT=$(grep -rn "TODO\|FIXME" apps/ --include="*.ts" --include="*.tsx" 2>/dev/null | grep -v node_modules | wc -l)
echo "**Total TODOs:** $TODO_COUNT" >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"

# ============================================================================
# Brand drift check
# ============================================================================
echo "## Brand drift status" >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"

OLD_FONTS=$(grep -r "NotoSansOsage\|TANNimbus" apps/ 2>/dev/null | grep -v node_modules | wc -l)
OLD_COLORS=$(grep -r "#2563EB\|#2B51E3" apps/ 2>/dev/null | grep -v node_modules | wc -l)

echo "- Old font references (NotoSansOsage, TANNimbus): **$OLD_FONTS**" >> "$STATUS_FILE"
echo "  - Target: 0 (replace with BeVietnamPro-Bold, Sentient-Medium)" >> "$STATUS_FILE"
echo "- Old color references (#2563EB, #2B51E3): **$OLD_COLORS**" >> "$STATUS_FILE"
echo "  - Target: 0 (replace with #2D79BF)" >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"

if [ "$OLD_FONTS" -gt 0 ] || [ "$OLD_COLORS" -gt 0 ]; then
  echo "⚠️ **Brand drift present.** Week 1 cleanup task." >> "$STATUS_FILE"
  echo "" >> "$STATUS_FILE"
fi

# ============================================================================
# Migration status
# ============================================================================
echo "## Database migrations" >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"
if [ -d "packages/db/migrations" ]; then
  echo '```' >> "$STATUS_FILE"
  ls -1 packages/db/migrations/ 2>/dev/null | head -20 >> "$STATUS_FILE"
  echo '```' >> "$STATUS_FILE"
else
  echo "migrations folder not found at packages/db/migrations/" >> "$STATUS_FILE"
fi
echo "" >> "$STATUS_FILE"

# ============================================================================
# Deploy status (health checks)
# ============================================================================
echo "## Deploy status" >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"

# API health (|| true prevents set -e from killing script on curl network failure)
API_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 https://api.rentrayda.com/health 2>/dev/null || true)
if [ -z "$API_STATUS" ] || [ "$API_STATUS" = "000" ]; then API_STATUS="unreachable"; fi
echo "- API (api.rentrayda.com/health): **$API_STATUS**" >> "$STATUS_FILE"

# Web health
WEB_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 https://rentrayda.com 2>/dev/null || true)
if [ -z "$WEB_STATUS" ] || [ "$WEB_STATUS" = "000" ]; then WEB_STATUS="unreachable"; fi
echo "- Web (rentrayda.com): **$WEB_STATUS**" >> "$STATUS_FILE"

# Landing page
FAST_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 https://rentrayda.com/fast 2>/dev/null || true)
if [ -z "$FAST_STATUS" ] || [ "$FAST_STATUS" = "000" ]; then FAST_STATUS="unreachable"; fi
echo "- Validation landing (/fast): **$FAST_STATUS**" >> "$STATUS_FILE"

echo "" >> "$STATUS_FILE"

# ============================================================================
# Test coverage (when tests exist)
# ============================================================================
echo "## Tests" >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"
TEST_COUNT=$(find apps/ packages/ -name "*.test.ts" -o -name "*.test.tsx" -o -name "*.spec.ts" -o -name "*.spec.tsx" 2>/dev/null | grep -v node_modules | wc -l)
echo "**Test files found:** $TEST_COUNT" >> "$STATUS_FILE"
if [ "$TEST_COUNT" -eq 0 ]; then
  echo "" >> "$STATUS_FILE"
  echo "⚠️ No tests exist yet. Foundation + smoke test is a Week 1 task." >> "$STATUS_FILE"
fi
echo "" >> "$STATUS_FILE"

# ============================================================================
# Known issues from REPO_STATUS baseline (manually curated)
# ============================================================================
echo "## Known unfixed issues (from REPO_STATUS.md baseline)" >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"

# These are checked dynamically where possible

# Check if resend is in package.json
RESEND_STATUS="unknown"
if [ -f "apps/api/package.json" ]; then
  if grep -q '"resend"' apps/api/package.json 2>/dev/null; then
    RESEND_STATUS="✅ installed"
  else
    RESEND_STATUS="❌ missing (imported but not in package.json)"
  fi
fi
echo "- resend package: $RESEND_STATUS" >> "$STATUS_FILE"

# Check for Sentry
SENTRY_STATUS="unknown"
if grep -q "@sentry/node\|@sentry/nextjs\|@sentry/react-native" apps/api/package.json apps/web/package.json apps/mobile/package.json 2>/dev/null; then
  SENTRY_STATUS="✅ installed"
else
  SENTRY_STATUS="❌ missing"
fi
echo "- Sentry integration: $SENTRY_STATUS" >> "$STATUS_FILE"

# Check for ESLint
ESLINT_STATUS="unknown"
if grep -q '"eslint"' package.json apps/*/package.json packages/*/package.json 2>/dev/null; then
  ESLINT_STATUS="✅ configured"
else
  ESLINT_STATUS="❌ not configured"
fi
echo "- ESLint: $ESLINT_STATUS" >> "$STATUS_FILE"

echo "" >> "$STATUS_FILE"

# ============================================================================
# Summary
# ============================================================================
echo "## Summary" >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"
echo "Refresh completed: $(date '+%Y-%m-%d %H:%M:%S')" >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"
echo "Next steps: See FINAL_DECISION.md Section 4 (Build List) and Section 8 (Full Build Plan)." >> "$STATUS_FILE"

echo "✓ Refreshed $STATUS_FILE"
echo ""
echo "Current counts:"
echo "  TODOs: $TODO_COUNT"
echo "  Old font refs: $OLD_FONTS"
echo "  Old color refs: $OLD_COLORS"
echo "  Test files: $TEST_COUNT"
echo ""
echo "Deploy status:"
echo "  API: $API_STATUS"
echo "  Web: $WEB_STATUS"
echo "  /fast landing: $FAST_STATUS"
